# ==========================================
# Root Outputs Definition
# Outputs expose information about the infrastructure that Terraform just built.
# Here we take the complex outputs generated by our child modules and simply 
# bubble them up to the root level so they print to the console when `terraform apply` finishes.
# ==========================================

output "divisions" {
  description = "Consolidated details (IDs and Names) of all created Divisions"
  value       = module.divisions.division_details # Pulls the `division_details` output from the `divisions` module
}

output "skills" {
  description = "Consolidated details (IDs and Names) of all created Routing Skills"
  value       = module.skills.skill_details
}

output "queues" {
  description = "Consolidated details (IDs and Names) of all created Routing Queues"
  value       = module.queues.queue_details # Pulls the `queue_details` output from the `queues` module
}

output "users" {
  description = "Consolidated details (IDs and Names) of all created Users"
  value       = module.users.user_details # Pulls the `user_details` output from the `users` module
}

output "roles" {
  description = "Consolidated details (IDs and Names) of all created Authorization Roles"
  value       = module.roles.role_details # Pulls the `role_details` output from the `roles` module
}

